<?php
return [
    [
        'id'          => 'boys-teams',
        'title'       => 'Boys Teams',
        'date'        => '2025 Season',
        'description' => 'Team CURE boys basketball teams.',
        'photos'      => [
            ['src' => 'assets/gallery/boys-teams/Birch 6th.jpg',          'alt' => 'Birch 6th Grade'],
            ['src' => 'assets/gallery/boys-teams/Bruno 7th.jpg',          'alt' => 'Bruno 7th Grade'],
            ['src' => 'assets/gallery/boys-teams/Coon HS.jpg',            'alt' => 'Coon High School'],
            ['src' => 'assets/gallery/boys-teams/Franceschelli 4th.jpg',  'alt' => 'Franceschelli 4th Grade'],
            ['src' => 'assets/gallery/boys-teams/Gensler 7th.jpg',        'alt' => 'Gensler 7th Grade'],
            ['src' => 'assets/gallery/boys-teams/Hippley 4th.jpg',        'alt' => 'Hippley 4th Grade'],
            ['src' => 'assets/gallery/boys-teams/Marmo 4th.jpg',          'alt' => 'Marmo 4th Grade'],
            ['src' => 'assets/gallery/boys-teams/Nittoli HS.jpg',         'alt' => 'Nittoli High School'],
            ['src' => 'assets/gallery/boys-teams/Parson 8th.jpg',         'alt' => 'Parson 8th Grade'],
            ['src' => 'assets/gallery/boys-teams/Pondillo 7th.jpg',       'alt' => 'Pondillo 7th Grade'],
            ['src' => 'assets/gallery/boys-teams/Reynolds 6th.jpg',       'alt' => 'Reynolds 6th Grade'],
            ['src' => 'assets/gallery/boys-teams/Roddy 8th.jpg',          'alt' => 'Roddy 8th Grade'],
            ['src' => 'assets/gallery/boys-teams/Sarver 3rd.jpg',         'alt' => 'Sarver 3rd Grade'],
            ['src' => 'assets/gallery/boys-teams/Sarver 6th.jpg',         'alt' => 'Sarver 6th Grade'],
            ['src' => 'assets/gallery/boys-teams/Turner 5th.jpg',         'alt' => 'Turner 5th Grade'],
            ['src' => 'assets/gallery/boys-teams/Venrose 6th.jpg',        'alt' => 'Venrose 6th Grade'],
        ],
    ],
    [
        'id'          => 'girls-teams',
        'title'       => 'Girls Teams',
        'date'        => '2025 Season',
        'description' => 'Team CURE girls basketball teams.',
        'photos'      => [
            ['src' => 'assets/gallery/Girls Team/Black 10th.jpg',       'alt' => 'Black 10th Grade'],
            ['src' => 'assets/gallery/Girls Team/Blue 8th.jpg',         'alt' => 'Blue 8th Grade'],
            ['src' => 'assets/gallery/Girls Team/Blundo 6th.jpg',       'alt' => 'Blundo 6th Grade'],
            ['src' => 'assets/gallery/Girls Team/Doran 4th.jpg',        'alt' => 'Doran 4th Grade'],
            ['src' => 'assets/gallery/Girls Team/Her-icanes 7th.jpg',   'alt' => 'Her-icanes 7th Grade'],
            ['src' => 'assets/gallery/Girls Team/Pink 10th.jpg',        'alt' => 'Pink 10th Grade'],
            ['src' => 'assets/gallery/Girls Team/Stubbs 7th.jpg',       'alt' => 'Stubbs 7th Grade'],
            ['src' => 'assets/gallery/Girls Team/Tropics 9th.jpg',      'alt' => 'Tropics 9th Grade'],
            ['src' => 'assets/gallery/Girls Team/Yellow 7th.jpg',       'alt' => 'Yellow 7th Grade'],
        ],
    ],
    [
        'id'          => 'golf-tournament',
        'title'       => 'Golf Tournament',
        'date'        => '2025',
        'description' => 'Team CURE Golf Tournament.',
        'photos'      => [
            ['src' => 'assets/golf/TC golf outing with sign.jpg', 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/TC golf outing.jpg',           'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7016.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7017.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7018.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7019.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7020.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7021.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7022.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7023.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7024.JPG',                 'alt' => 'Golf Tournament'],
            ['src' => 'assets/golf/IMG_7025.JPG',                 'alt' => 'Golf Tournament'],
        ],
    ],
];
